//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmeFace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsmeFace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3Security {
            get {
                object obj = ResourceManager.GetObject("3Security", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена успешно!\r\nЧтобы узнать график сотрудника\r\nВыберите отдел.
        /// </summary>
        internal static string ACCESSFORM_SUCCESS_INFO {
            get {
                return ResourceManager.GetString("ACCESSFORM_SUCCESS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип устройство.
        /// </summary>
        internal static string CONTROL_DEVICE_CHOOSE_TYPE {
            get {
                return ResourceManager.GetString("CONTROL_DEVICE_CHOOSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите направления.
        /// </summary>
        internal static string CONTROL_DEVICE_SELECT_DIRECTION {
            get {
                return ResourceManager.GetString("CONTROL_DEVICE_SELECT_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дверь.
        /// </summary>
        internal static string CONTROL_DEVICE_SELECT_DOOR {
            get {
                return ResourceManager.GetString("CONTROL_DEVICE_SELECT_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число должна быть установлена ​​на будущее.
        /// </summary>
        internal static string CONTROL_GRAFIK_STAFF_DATE_RANGE_WARNING {
            get {
                return ResourceManager.GetString("CONTROL_GRAFIK_STAFF_DATE_RANGE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У сотрудника есть график в этом периоде\r\n.
        /// </summary>
        internal static string CONTROL_GRAFIK_STAFF_EMP_HAS_SHIFT {
            get {
                return ResourceManager.GetString("CONTROL_GRAFIK_STAFF_EMP_HAS_SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена успешно!\r\nЧтобы узнать график сотрудника\r\nвыберите период времени и отдел.
        /// </summary>
        internal static string CONTROL_GRAFIK_STAFF_SUCCESS_INFO {
            get {
                return ResourceManager.GetString("CONTROL_GRAFIK_STAFF_SUCCESS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить язык?.
        /// </summary>
        internal static string CONTROL_LANGUAGE_CHANGE {
            get {
                return ResourceManager.GetString("CONTROL_LANGUAGE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдел.
        /// </summary>
        internal static string CONTROL_STAFF_DEPARTMENT {
            get {
                return ResourceManager.GetString("CONTROL_STAFF_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to количество сотрудников:.
        /// </summary>
        internal static string CONTROL_STAFF_EMPLOYEE_COUNT {
            get {
                return ResourceManager.GetString("CONTROL_STAFF_EMPLOYEE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не удалась. Для получения дополнительной информации см. Файл &lt;Log&gt;.
        /// </summary>
        internal static string DEVICE_FAILED_INFO {
            get {
                return ResourceManager.GetString("DEVICE_FAILED_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось открыть устройство.
        /// </summary>
        internal static string DEVICE_FAILED_OPEN {
            get {
                return ResourceManager.GetString("DEVICE_FAILED_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено.
        /// </summary>
        internal static string DOOR_CONTROL_FINISHED {
            get {
                return ResourceManager.GetString("DOOR_CONTROL_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизируется .....
        /// </summary>
        internal static string DOOR_CONTROL_SYNCING {
            get {
                return ResourceManager.GetString("DOOR_CONTROL_SYNCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить дверь?.
        /// </summary>
        internal static string DOORS_DELETE_DOOR {
            get {
                return ResourceManager.GetString("DOORS_DELETE_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить дверь?.
        /// </summary>
        internal static string DOORS_EDIT_DOOR {
            get {
                return ResourceManager.GetString("DOORS_EDIT_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить дверь невозможно \nДверь используется.
        /// </summary>
        internal static string DOORS_IN_USE {
            get {
                return ResourceManager.GetString("DOORS_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График существует.
        /// </summary>
        internal static string EXIST {
            get {
                return ResourceManager.GetString("EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните все обязательные поля.
        /// </summary>
        internal static string FILL_IN_ALL_FIELDS {
            get {
                return ResourceManager.GetString("FILL_IN_ALL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ранный уход.
        /// </summary>
        internal static string GRAFIK_VIEW_BREAK_EARLY {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_BREAK_EARLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание прерыва.
        /// </summary>
        internal static string GRAFIK_VIEW_BREAK_END {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_BREAK_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опоздание.
        /// </summary>
        internal static string GRAFIK_VIEW_BREAK_LATE {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_BREAK_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало прерыва.
        /// </summary>
        internal static string GRAFIK_VIEW_BREAK_START {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_BREAK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число.
        /// </summary>
        internal static string GRAFIK_VIEW_DATE {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        internal static string GRAFIK_VIEW_DAY {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание.
        /// </summary>
        internal static string GRAFIK_VIEW_FINISH {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string GRAFIK_VIEW_START {
            get {
                return ResourceManager.GetString("GRAFIK_VIEW_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        internal static string LOGIN_WRONG {
            get {
                return ResourceManager.GetString("LOGIN_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не удалось.
        /// </summary>
        internal static string OPERATION_FAILED {
            get {
                return ResourceManager.GetString("OPERATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено успешно!.
        /// </summary>
        internal static string OPERATION_SUCCESS {
            get {
                return ResourceManager.GetString("OPERATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        internal static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль.
        /// </summary>
        internal static string PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quant {
            get {
                object obj = ResourceManager.GetObject("quant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quantum {
            get {
                object obj = ResourceManager.GetObject("Quantum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена существует.
        /// </summary>
        internal static string SCHEDULE_EXIST {
            get {
                return ResourceManager.GetString("SCHEDULE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите график.
        /// </summary>
        internal static string SHIFT_CHOOSE {
            get {
                return ResourceManager.GetString("SHIFT_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График используется.
        /// </summary>
        internal static string SHIFT_IN_USE {
            get {
                return ResourceManager.GetString("SHIFT_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap staff {
            get {
                object obj = ResourceManager.GetObject("staff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap staff_add {
            get {
                object obj = ResourceManager.GetObject("staff_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uk {
            get {
                object obj = ResourceManager.GetObject("uk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждения.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
